name: Deploy Static Site

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              run: |
                  npm install

            # Run ESLint before deployment
            - name: Run ESLint
              run: |
                  npx eslint . --ext .js
              continue-on-error: false # Ensures deployment stops if ESLint finds an error

            - name: Build and Deploy to GitHub Pages
              run: |
                  npm run build
                  git remote add origin https://github.com/${{ github.repository }}.git
                  git push --force origin main

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
